export type Opportunity = {
  id: string;
  name: string;
  org: string;
  short: string;
  description: string;
  category: string;
  industry: string;
  stage: string;
  location: string;
  amount: string;
  deadline: string;
  eligibility: string;
  logo: string;
  sourceUrl?: string | null;
  tags?: string[];
};

export const defaultCategories = [
  "Startup Credits",
  "Grants",
  "Accelerators",
  "Incubators",
  "Government Schemes",
  "Fellowships",
  "Competitions",
  "Investor Programs",
] as const;

export type OpportunityCategory = typeof defaultCategories[number];

export function slugify(s: string) {
  return s
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "")
    .slice(0, 60);
}

export const seedOpportunities: Opportunity[] = [
  {
    id: "aws-activate",
    name: "AWS Activate Credits",
    org: "Amazon Web Services",
    short: "Up to $100,000 in AWS credits for eligible startups.",
    description:
      "AWS Activate provides startups with the resources needed to get started on AWS — including AWS credits, technical support, and training.",
    category: "Startup Credits",
    industry: "SaaS",
    stage: "Seed",
    location: "Global",
    amount: "Up to ₹83,00,000",
    deadline: "Rolling",
    eligibility: "Privately held, <10 yrs old, <$100M funding.",
    logo: "A",
    sourceUrl: "https://aws.amazon.com/activate/",
  },
  {
    id: "microsoft-for-startups",
    name: "Microsoft for Startups",
    org: "Microsoft",
    short: "Azure credits, GitHub Enterprise, and go-to-market support.",
    description:
      "The Microsoft for Startups Founders Hub offers up to $150K in Azure credits along with access to Microsoft technologies, mentorship, and customer connections.",
    category: "Startup Credits",
    industry: "SaaS",
    stage: "Pre-Seed",
    location: "Global",
    amount: "Up to ₹1,24,50,000",
    deadline: "Rolling",
    eligibility: "B2B/B2C startups building software.",
    logo: "M",
    sourceUrl: "https://www.microsoft.com/en-us/startups",
  },
  {
    id: "startup-india-seed-fund",
    name: "Startup India Seed Fund Scheme",
    org: "Government of India",
    short: "Seed funding to startups for proof of concept and prototype.",
    description:
      "SISFS provides financial assistance to startups for proof of concept, prototype development, product trials, market entry and commercialization.",
    category: "Government Schemes",
    industry: "All",
    stage: "Pre-Seed",
    location: "India",
    amount: "Up to ₹50,00,000",
    deadline: "Mar 31, 2026",
    eligibility: "DPIIT-recognized startup, <2 yrs old.",
    logo: "G",
    sourceUrl: "https://seedfund.startupindia.gov.in/",
  },
  {
    id: "nasscom-10k",
    name: "NASSCOM 10K Startups",
    org: "NASSCOM",
    short: "Incubation, mentorship and market access for tech startups.",
    description:
      "NASSCOM 10K Startups is an industry-led initiative aiming to scale up 10,000 startups in India over the next decade.",
    category: "Incubators",
    industry: "Deep Tech",
    stage: "Seed",
    location: "India",
    amount: "Up to ₹25,00,000",
    deadline: "Jan 20, 2026",
    eligibility: "Indian tech startups <5 yrs old.",
    logo: "N",
    sourceUrl: "https://10000startups.com/",
  },
  {
    id: "birac-big",
    name: "BIRAC BIG Grant",
    org: "BIRAC",
    short: "Biotechnology Ignition Grant for early-stage biotech startups.",
    description:
      "BIG supports innovative ideas with commercial potential in the biotech space with grant-in-aid of up to ₹50 lakhs.",
    category: "Grants",
    industry: "Biotech",
    stage: "Pre-Seed",
    location: "India",
    amount: "Up to ₹50,00,000",
    deadline: "Feb 14, 2026",
    eligibility: "Indian biotech innovators, individuals or startups.",
    logo: "B",
    sourceUrl: "https://birac.nic.in/desc_new.php?id=364",
  },
  {
    id: "yc-india-track",
    name: "Y Combinator (India)",
    org: "Y Combinator",
    short: "3-month accelerator program with $500K investment.",
    description:
      "YC funds startups twice a year. Companies receive $500,000 in investment, plus access to mentors and an alumni network.",
    category: "Accelerators",
    industry: "All",
    stage: "Pre-Seed",
    location: "Remote / SF",
    amount: "₹4,15,00,000",
    deadline: "Apr 12, 2026",
    eligibility: "Any startup with a working team.",
    logo: "Y",
    sourceUrl: "https://www.ycombinator.com/apply",
  },
  {
    id: "google-for-startups",
    name: "Google for Startups Cloud Program",
    org: "Google",
    short: "Up to $200,000 in Google Cloud credits over two years.",
    description:
      "Cloud credits, technical training, and Google-wide support for AI-first and Series A startups.",
    category: "Startup Credits",
    industry: "AI",
    stage: "Seed",
    location: "Global",
    amount: "Up to ₹1,66,00,000",
    deadline: "Rolling",
    eligibility: "Funded startups <5 yrs old.",
    logo: "G",
    sourceUrl: "https://cloud.google.com/startup",
  },
  {
    id: "tdb-grant",
    name: "Technology Development Board Grant",
    org: "TDB, Govt. of India",
    short: "Financial assistance to commercialize indigenous technology.",
    description:
      "TDB provides equity capital or loans to industrial concerns and other agencies for the development and commercialization of indigenous technology.",
    category: "Grants",
    industry: "Deep Tech",
    stage: "Series A",
    location: "India",
    amount: "Up to ₹5,00,00,000",
    deadline: "Mar 30, 2026",
    eligibility: "Indian companies commercializing tech.",
    logo: "T",
    sourceUrl: "https://tdb.gov.in/",
  },
  {
    id: "tie-grand-challenge",
    name: "TiE Global Grand Challenge",
    org: "TiE",
    short: "Global startup competition with cash prizes and investor access.",
    description:
      "Annual competition recognizing high-impact startups across sectors with cash prizes, mentorship, and global investor exposure.",
    category: "Competitions",
    industry: "All",
    stage: "Seed",
    location: "Global",
    amount: "Up to ₹40,00,000",
    deadline: "Feb 28, 2026",
    eligibility: "Startups <7 yrs, revenue <$5M.",
    logo: "T",
    sourceUrl: "https://tie.org/",
  },
  {
    id: "atal-incubation",
    name: "Atal Incubation Centre",
    org: "NITI Aayog",
    short: "Government-backed incubation across India.",
    description:
      "AICs nurture innovative startups in their pursuit to become scalable and sustainable business enterprises.",
    category: "Incubators",
    industry: "All",
    stage: "Pre-Seed",
    location: "India",
    amount: "Up to ₹10,00,00,000",
    deadline: "Rolling",
    eligibility: "Indian startups across sectors.",
    logo: "A",
    sourceUrl: "https://aim.gov.in/atal-incubation-centres.php",
  },
  {
    id: "chevening",
    name: "Chevening Fellowship",
    org: "UK Government",
    short: "Fully-funded fellowship for emerging leaders.",
    description:
      "Chevening offers fully funded fellowships in the UK for outstanding individuals with leadership potential.",
    category: "Fellowships",
    industry: "All",
    stage: "Any",
    location: "United Kingdom",
    amount: "Fully Funded",
    deadline: "Nov 5, 2026",
    eligibility: "Founders with 2+ yrs work experience.",
    logo: "C",
    sourceUrl: "https://www.chevening.org/fellowships/",
  },
  {
    id: "sequoia-surge",
    name: "Peak XV Surge",
    org: "Peak XV Partners",
    short: "Rapid scale-up program with $3M investment.",
    description:
      "Surge is a 16-week rapid scale-up program for early-stage startups across Asia.",
    category: "Investor Programs",
    industry: "All",
    stage: "Seed",
    location: "India / SEA",
    amount: "₹24,90,00,000",
    deadline: "Jan 31, 2026",
    eligibility: "Early-stage startups in Asia.",
    logo: "P",
    sourceUrl: "https://www.surgeahead.com/",
  },
  {
    id: "maarg-mentorship",
    name: "MAARG Mentorship Program",
    org: "Startup India / DPIIT",
    short: "Free mentorship from 900+ domain experts for DPIIT-recognised startups.",
    description:
      "MAARG (Mentorship, Advisory, Assistance, Resilience and Growth) is a national mentorship portal connecting startups with expert mentors across 150+ domains including product, legal, finance, marketing, and deep tech. Sessions are free and mentor-led.",
    category: "Government Schemes",
    industry: "All",
    stage: "Pre-Seed",
    location: "India",
    amount: "Free",
    deadline: "Rolling",
    eligibility: "DPIIT-recognised startups.",
    logo: "M",
    sourceUrl: "https://www.startupindia.gov.in/content/sih/en/maarg.html",
  },
  {
    id: "credit-guarantee-startups",
    name: "Credit Guarantee Fund Scheme for Startups",
    org: "NCGTC / DPIIT",
    short: "Government credit guarantee on loans up to ₹20 crore for DPIIT-recognised startups.",
    description:
      "CGSS provides credit guarantees via NCGTC to loans extended by scheduled commercial banks, NBFCs, and Venture Debt Funds to DPIIT-recognised startups. Eligible instruments include venture debt, working capital, subordinated debt, and debentures. Guarantee coverage is up to ₹20 crore per startup.",
    category: "Government Schemes",
    industry: "All",
    stage: "Seed",
    location: "India",
    amount: "Guarantee up to ₹20 crore",
    deadline: "Rolling",
    eligibility: "DPIIT-recognised startup. Applied through partner banks/NBFCs/VDFs.",
    logo: "C",
    sourceUrl: "https://www.startupindia.gov.in/content/sih/en/credit-guarantee-scheme-for-startups.html",
  },
  {
    id: "wep-women-entrepreneurs",
    name: "Women Entrepreneurship Platform (WEP)",
    org: "NITI Aayog / Startup India",
    short: "Unified portal for funding, mentorship, and market access for women-led startups.",
    description:
      "WEP aggregates resources from central ministries, state governments, and private partners for women entrepreneurs. Provides funding connect to women-focused investors, 500+ mentors, skilling programs, and GeM marketplace linkage. Linked to Mudra Yojana (up to ₹10L) and Stand-Up India (up to ₹1Cr for SC/ST women).",
    category: "Government Schemes",
    industry: "All",
    stage: "Pre-Seed",
    location: "India",
    amount: "Up to ₹1,00,00,000",
    deadline: "Rolling",
    eligibility: "Women entrepreneurs; some schemes require SC/ST status.",
    logo: "W",
    sourceUrl: "https://wep.gov.in/",
  },
  {
    id: "fund-of-funds-startups",
    name: "Fund of Funds for Startups (FFS)",
    org: "SIDBI / DPIIT",
    short: "₹10,000 crore government corpus backing SEBI-registered AIFs that invest in startups.",
    description:
      "FFS is managed by SIDBI and invests in SEBI-registered Alternative Investment Funds (AIFs), which in turn invest in Indian startups. Over 100 AIFs have received FFS backing. The government does not invest directly — it provides anchor capital to VC funds with a 2:1 leverage requirement.",
    category: "Investor Programs",
    industry: "All",
    stage: "Seed",
    location: "India",
    amount: "Via SEBI-registered AIFs",
    deadline: "Rolling",
    eligibility: "Apply through FFS-backed AIF funds (listed on SIDBI website).",
    logo: "F",
    sourceUrl: "https://www.sidbi.in/en/",
  },
  {
    id: "bharat-startup-grand-challenge",
    name: "Bharat Startup Grand Challenge",
    org: "Startup India / DPIIT",
    short: "National challenge for startups solving India's most pressing problems.",
    description:
      "An initiative to identify and support startups working on critical national challenges across sectors like water, energy, health, and agriculture. Winners receive funding support, government mentorship, and facilitation for pilot projects with government departments.",
    category: "Competitions",
    industry: "All",
    stage: "Pre-Seed",
    location: "India",
    amount: "Up to ₹30,00,000",
    deadline: "Rolling",
    eligibility: "DPIIT-recognised startups working on national challenges.",
    logo: "B",
    sourceUrl: "https://www.startupindia.gov.in/content/sih/en/bharat-startup-grand-challenge.html",
  },
  {
    id: "national-startup-awards",
    name: "National Startup Awards (NSA)",
    org: "DPIIT / Startup India",
    short: "Annual awards recognising exceptional Indian startups across 20+ sectors.",
    description:
      "NSA is India's flagship startup recognition program run by DPIIT. Winners receive a cash prize of ₹5 lakh per category, national visibility, government mentorship, and facilitation for pilots with central ministries. Open to all DPIIT-recognised startups across sectors.",
    category: "Competitions",
    industry: "All",
    stage: "Seed",
    location: "India",
    amount: "₹5,00,000 cash prize + support",
    deadline: "Annual (applications open ~Aug)",
    eligibility: "DPIIT-recognised startup, operational for at least 1 year.",
    logo: "N",
    sourceUrl: "https://www.startupindia.gov.in/content/sih/en/nsa-landing.html",
  },
  {
    id: "atal-incubation-centre",
    name: "Atal Incubation Centres (AIC)",
    org: "NITI Aayog / AIM",
    short: "Government-backed incubators with up to ₹10 crore in grant funding, across 72+ locations in India.",
    description:
      "Atal Innovation Mission operates 72+ Atal Incubation Centres across India. AICs receive up to ₹10 crore in government grants and provide office space, equipment, mentorship, seed funding, and DPIIT-network access. Sectors vary by AIC.",
    category: "Incubators",
    industry: "All",
    stage: "Pre-Seed",
    location: "India",
    amount: "Incubation + seed support",
    deadline: "Rolling (cohort-based)",
    eligibility: "Early-stage Indian startups. Apply to individual AIC website.",
    logo: "A",
    sourceUrl: "https://aim.gov.in/atal-incubation-centres.php",
  },
  {
    id: "thub-hyderabad",
    name: "T-Hub Hyderabad",
    org: "T-Hub",
    short: "India's largest startup incubator, backed by Telangana government.",
    description:
      "T-Hub is India's largest startup innovation ecosystem, backed by the Government of Telangana and three premier institutions — IIIT-Hyderabad, ISB, and NALSAR. Provides co-working, industry connects, investor access, and go-to-market support.",
    category: "Accelerators",
    industry: "SaaS",
    stage: "Seed",
    location: "Hyderabad",
    amount: "Equity-free incubation",
    deadline: "Rolling",
    eligibility: "Tech startups, preference for Telangana-based but open nationally.",
    logo: "T",
    sourceUrl: "https://t-hub.co/",
  },
  {
    id: "nsrcel-iim-bangalore",
    name: "NSRCEL — IIM Bangalore",
    org: "IIM Bangalore",
    short: "Flagship incubator of IIM Bangalore, supporting high-potential startups with mentorship and funding access.",
    description:
      "NSRCEL (N.S. Raghavan Centre for Entrepreneurial Learning) is IIM Bangalore's startup incubator. Offers the Goldman Sachs 10,000 Women program, GYAAN Incubation (social impact), and STEM cohorts for deep tech startups. Provides mentorship from IIM faculty and alumni investors.",
    category: "Incubators",
    industry: "All",
    stage: "Pre-Seed",
    location: "Bangalore",
    amount: "Equity-free + seed grant",
    deadline: "Cohort-based",
    eligibility: "Early-stage startups with traction or strong PoC.",
    logo: "N",
    sourceUrl: "https://nsrcel.org/",
  },
  {
    id: "kerala-startup-mission",
    name: "Kerala Startup Mission (KSUM)",
    org: "Government of Kerala",
    short: "State nodal agency for technology startups in Kerala — incubation, seed fund, and ecosystem support.",
    description:
      "KSUM is the Government of Kerala's nodal agency for startups. It operates 20+ incubators, provides pre-seed grants (up to ₹5 lakh for student startups), seed funding (up to ₹15 lakh), and connects startups to the Kerala government's public sector for pilot projects.",
    category: "Incubators",
    industry: "Deep Tech",
    stage: "Pre-Seed",
    location: "Kerala",
    amount: "Up to ₹15,00,000",
    deadline: "Rolling",
    eligibility: "Startups based in Kerala or willing to relocate.",
    logo: "K",
    sourceUrl: "https://startupmission.kerala.gov.in/",
  },
  {
    id: "sine-iit-bombay",
    name: "SINE — IIT Bombay",
    org: "IIT Bombay",
    short: "IIT Bombay's technology business incubator — access to labs, IP, faculty mentors, and investor network.",
    description:
      "Society for Innovation and Entrepreneurship (SINE) at IIT Bombay is one of India's top deep tech incubators. Provides access to IIT Bombay's research labs, patented IP licensing, faculty co-founders, and a network of 3,000+ alumni investors. Strong in medtech, cleantech, and enterprise software.",
    category: "Incubators",
    industry: "Deep Tech",
    stage: "Pre-Seed",
    location: "Mumbai",
    amount: "Lab access + seed grant",
    deadline: "Rolling",
    eligibility: "Deep tech startups with IIT Bombay IP or faculty co-founders preferred.",
    logo: "S",
    sourceUrl: "https://www.sineiitb.org/",
  },
  {
    id: "wadhwani-foundation",
    name: "Wadhwani Foundation Startup Program",
    org: "Wadhwani Foundation",
    short: "Non-profit accelerator backing early-stage startups with mentorship, capital connects, and talent programs.",
    description:
      "Wadhwani Foundation runs accelerator programs across India focused on job creation. Programs include NEN (National Entrepreneurship Network) for campus entrepreneurs and the Startup Program for growth-stage startups. Provides business development support, IP guidance, and introductions to corporate partners.",
    category: "Accelerators",
    industry: "All",
    stage: "Pre-Seed",
    location: "India",
    amount: "Equity-free support",
    deadline: "Rolling",
    eligibility: "Startups with demonstrated early traction.",
    logo: "W",
    sourceUrl: "https://www.wadhwani.org/",
  },
  {
    id: "india-accelerator",
    name: "India Accelerator",
    org: "India Accelerator",
    short: "Sector-agnostic accelerator with ₹25 lakh investment + mentorship for early-stage Indian startups.",
    description:
      "India Accelerator is a Gurgaon-based accelerator that invests ₹25 lakh for 5% equity in selected startups. Cohorts of 10–15 startups run for 4 months with 100+ mentors, corporate connections, and a demo day with 200+ investors.",
    category: "Accelerators",
    industry: "All",
    stage: "Pre-Seed",
    location: "Gurgaon",
    amount: "₹25,00,000 for 5% equity",
    deadline: "Cohort-based",
    eligibility: "Early-stage startups with a working prototype.",
    logo: "I",
    sourceUrl: "https://indiaaccelerator.co/",
  },
  {
    id: "birac-sparsh",
    name: "BIRAC SPARSH Program",
    org: "BIRAC",
    short: "Social innovation grant for biotech startups creating impact for underserved communities.",
    description:
      "SPARSH (Social innovation Programme for products, research and services in health) supports biotech startups developing products and services for underserved populations in health, agriculture, and environment. Grant-in-aid up to ₹50 lakh for proof-of-concept and prototype stage.",
    category: "Grants",
    industry: "Biotech",
    stage: "Pre-Seed",
    location: "India",
    amount: "Up to ₹50,00,000",
    deadline: "Rolling",
    eligibility: "Indian biotech startups; social impact focus required.",
    logo: "B",
    sourceUrl: "https://birac.nic.in/",
  },
  {
    id: "dst-nidhi",
    name: "DST-NIDHI PRAYAS Grant",
    org: "Department of Science & Technology",
    short: "Pre-incubation grant of ₹10 lakh for innovators to develop first working prototypes.",
    description:
      "NIDHI-PRAYAS (Promoting and Accelerating Young and Aspiring innovators) provides grants of up to ₹10 lakh to individual innovators and early-stage startups to convert their ideas into physical prototypes. Disbursed through 20+ PRAYAS Centres hosted by incubators across India.",
    category: "Grants",
    industry: "Deep Tech",
    stage: "Pre-Seed",
    location: "India",
    amount: "Up to ₹10,00,000",
    deadline: "Rolling",
    eligibility: "Indian individual innovators or startups at idea/early prototype stage.",
    logo: "D",
    sourceUrl: "https://nidhi.dst.gov.in/",
  },
];
