export type StpiCenter = {
  city: string;
  address: string;
  plugAndPlay?: number;
  rawSpaceSqft?: number;
};

export const stpiCenters: StpiCenter[] = [
  { city: "Agartala", address: "3rd Floor IT Bhavan, Indranagar, Agartala Tripura 799006", plugAndPlay: 220, rawSpaceSqft: 6966 },
  { city: "Agra", address: "Sector-D, Sashtripuram, Agra Development Authority Yojna, Agra - 282007 (UP)", plugAndPlay: 102, rawSpaceSqft: 2330 },
  { city: "Amritsar", address: "Plot A-9, Industrial Focal Point Extn-III, Amritsar Punjab - 143001", plugAndPlay: 197, rawSpaceSqft: 10198 },
  { city: "Balasore", address: "NOCCI Business Park, Bamapada Industrial Estate", plugAndPlay: 19 },
  { city: "Bengaluru", address: "No. 76, 77 Part 78, 3rd Floor, Electronic City Phase-1, Hosur Road, Bengaluru-560100", plugAndPlay: 169, rawSpaceSqft: 38600 },
  { city: "Berhampur", address: "Plot No. 860/4562 Ambapua, Near Income Tax Office, Berhampur - 760002 (Odisha)", rawSpaceSqft: 769 },
  { city: "Bhagalpur", address: "Backside of BIADA, Merrachak Road, Barari, Bhagalpur - 812001", plugAndPlay: 94 },
  { city: "Bhilai", address: "Mangal Bhavan, Nehru Nagar (E), Bhilai, Durg, Chattisgarh - 490020", plugAndPlay: 128, rawSpaceSqft: 15528 },
  { city: "Bhopal", address: "Plot No. C-11, IT Park, Near RGPV, New Jail Road, Gandhinagar, Bhopal 462036" },
  { city: "Bhubaneswar", address: "STPI ELITE Building, Plot No.2/A, IDCO Industrial Area, Gothapatna, Bhubaneswar 751003", plugAndPlay: 65, rawSpaceSqft: 57000 },
  { city: "Chennai", address: "No.5 III Floor, Rajiv Gandhi Salai Taramani, Chennai - 600113", plugAndPlay: 201, rawSpaceSqft: 44794 },
  { city: "Chhatrapati Sambhajinagar", address: "Plot T-25 MIDC, Chikal Thana, Chhatrapati Sambhajinagar - 431210", plugAndPlay: 12 },
  { city: "Darbhanga", address: "Govt. Industrial Training Women ITI, Ramnagara, Darbhanga", plugAndPlay: 76, rawSpaceSqft: 10000 },
  { city: "Davanagere", address: "KSOU Regional Centre, J.H Patel Layout, Naganur Road, Davanagere, Karnataka 577004", plugAndPlay: 102 },
  { city: "Dehradun", address: "Plot No. IT-01, Integrated Industrial Estate IT Park, Sahastradhara Road, Dehradun - 248013", rawSpaceSqft: 7839 },
  { city: "Deoghar", address: "Industrial Plot No. NS-15(P), Jasidih Industrial Area, Deoghar, Jharkhand", plugAndPlay: 64 },
  { city: "Dhanbad", address: "BIT, Sindri, Jharkhand 828120" },
  { city: "Durgapur", address: "Sahid Sukumar Banerjee Sarani, Near Rangan Guest House, Bidhan Nagar, Durgapur - 713212", plugAndPlay: 40 },
  { city: "Gandhinagar", address: "9th Floor, GIFT One Tower, Block 56, Road-5C, Gift City, Gandhinagar - 382355 Gujarat", plugAndPlay: 136 },
  { city: "Goa", address: "2nd Floor, Udyog Bhawan, Panaji, Goa 403001", plugAndPlay: 48 },
  { city: "Gorakhpur", address: "GIDA, Gorakhpur Industrial Development Authority, Sector-7, Gorakhpur, Uttar Pradesh", plugAndPlay: 48, rawSpaceSqft: 3605 },
  { city: "Gurugram", address: "Plot 30, Udhyog Vihar Phase IV, Sector 18, Electronic City, Gurugram 122015", plugAndPlay: 141, rawSpaceSqft: 8974 },
  { city: "Guwahati", address: "Near LGB Airport, Borjhar, Guwahati - 781015 (Assam)", rawSpaceSqft: 6007 },
  { city: "Haldia", address: "Plot No.149, Debhog, Bhabanipur, Purba Medinipur, Haldia - 721657", plugAndPlay: 41 },
  { city: "Hubballi", address: "4th Floor, IT Park, Opp. Indira Glass House, Hubballi - 580029", plugAndPlay: 20 },
  { city: "Hyderabad", address: "6Q3, 6th floor, Cyber Towers, Hitech City, Madhapur, Hyderabad - 500081", plugAndPlay: 364, rawSpaceSqft: 14489 },
  { city: "Imphal", address: "STPI Complex, Mantripukhi, National Highway 39, Imphal - 795001", rawSpaceSqft: 724 },
  { city: "Indore", address: "MPSEDC, STP Building, Electronics Complex, Pardeshipura, Indore - 452010", plugAndPlay: 20 },
  { city: "Itanagar", address: "Itanagar", plugAndPlay: 18 },
  { city: "Jaipur", address: "IT-21, IT Park, EPIP, Sitapura, Tonk Road, Jaipur-302022", plugAndPlay: 96, rawSpaceSqft: 5862 },
  { city: "Jammu", address: "GPI, E.P.I.P, Kartholi, Barbrahmna, Jammu - 181133", rawSpaceSqft: 3415 },
  { city: "Jodhpur", address: "Plot No. CYB-I, Cyber Park, RIICO Heavy Industrial Area, Near Saras Dairy, Jodhpur - 342003", rawSpaceSqft: 4606 },
  { city: "Kakinada", address: "Collectorate Compound, Kakinada - 533004 (AP)", plugAndPlay: 121 },
  { city: "Kanpur", address: "UPSIDC Complex, A-1/4 Lakhanpur, Kanpur-208024, U.P", plugAndPlay: 4, rawSpaceSqft: 2637 },
  { city: "Kharagpur", address: "WBIDC Industrial Growth Centre, Plot No. 3, Sector-B, Nimpura, Kharagpur - 721303", plugAndPlay: 11, rawSpaceSqft: 456 },
  { city: "Kochi", address: "Kinfra Hi-Tech Park, Near Govt Medical College, Kalamassery, Kochi - 683503", plugAndPlay: 135 },
  { city: "Kohima", address: "Directorate of IT & Communication, Thizama Road, Kohima, Nagaland - 797001", plugAndPlay: 85, rawSpaceSqft: 1258 },
  { city: "Kolkata", address: "Block No. DP Plot 5/1, Salt Lake Electronics Complex, Sector-5, Kolkata - 700091", plugAndPlay: 105, rawSpaceSqft: 44260 },
  { city: "Koraput", address: "Plot No. 505, Mouza Umuri, Jeypore (Koraput)", plugAndPlay: 76, rawSpaceSqft: 1014 },
  { city: "Lucknow", address: "STP Complex, Adjacent Gomti Barrage, Gomti Nagar, Lucknow - 226010", plugAndPlay: 26, rawSpaceSqft: 1440 },
  { city: "Mangaluru", address: "Survey No. 129/1A, Blueberry Hill, Derebail, Mangaluru-575008", plugAndPlay: 86, rawSpaceSqft: 900 },
  { city: "Meerut", address: "Plot No. IT P-03, Near NH58 Bypass, Ved Vyas Puri Yojna, Meerut 250002", plugAndPlay: 133, rawSpaceSqft: 1903 },
  { city: "Mohali", address: "Plot C-184, Industrial Area, Phase-8A, Sector 75, Mohali - 160071 Punjab", plugAndPlay: 100, rawSpaceSqft: 23682 },
  { city: "Mumbai", address: "Gala No. 4, 4th Floor, Samruddhi Venture Park, MIDC Central Road, Andheri (East), Mumbai - 400093", plugAndPlay: 53, rawSpaceSqft: 3500 },
  { city: "Mysuru", address: "SJCE-STEP Campus, Manas Gangothri, Mysuru - 570006", plugAndPlay: 104 },
  { city: "Nagpur", address: "Plot No. 3, IT Park, South Ambazari Road, Parsodi, Nagpur - 440022", plugAndPlay: 227 },
  { city: "Nashik", address: "IT-1, IT Park, MIDC, Ambad, Nashik" },
  { city: "Noida", address: "Block IV, Ganga Software Technology Complex, Sector 29, Noida - 201303 (U.P.)", plugAndPlay: 13 },
  { city: "Patna", address: "First Floor, Patliputra Colony, Rajeev Nagar Road, Near New Govt. Polytechnic College, Patna - 800013", plugAndPlay: 103, rawSpaceSqft: 51862 },
  { city: "Prayagraj", address: "MNIT Campus, Lucknow Road, Prayagraj - 211004 (Uttar Pradesh)", plugAndPlay: 46, rawSpaceSqft: 4930 },
  { city: "Pune", address: "Plot P-I, Rajiv Gandhi Infotech Park, MIDC Hinjawadi, Pune - 411057", plugAndPlay: 363, rawSpaceSqft: 7890 },
  { city: "Ranchi", address: "Plot No.8, Namkom Industrial Area, Ranchi-834001 Jharkhand", plugAndPlay: 62, rawSpaceSqft: 27171 },
  { city: "Rourkela", address: "Industrial Museum, Sector-5, Near I.G. Park, Rourkela-769002", rawSpaceSqft: 9646 },
  { city: "Shillong", address: "Lum Jing Shai, Short Round Road, Shillong - 793001 (Meghalaya)", rawSpaceSqft: 2225 },
  { city: "Shimla", address: "Khasra No. 93/1, Near Kamna Devi Temple, Boileauganj, Himachal Pradesh - 171005", plugAndPlay: 106, rawSpaceSqft: 20046 },
  { city: "Siliguri", address: "JL No. 86, Matigara, Dist. Darjeeling, Siliguri- 734010", plugAndPlay: 32 },
  { city: "Srinagar", address: "6, SIDCO Electronics Complex, Old Airport Road, Srinagar, Kashmir - 190007", rawSpaceSqft: 9789 },
  { city: "Surat", address: "FP 27, TP 22, Jiav Budia Road, Nr. Someshwar Society, Bhestan, Surat - 395023", plugAndPlay: 106 },
  { city: "Thiruvananthapuram", address: "STPI Building, Technopark, Karyavattom PO, Thiruvananthapuram - 695581", plugAndPlay: 188 },
  { city: "Tirupati", address: "Survey No. 234, Behind Urban Haat Tiruchanur Road, Tirupati - 517503 (AP)" },
  { city: "Vijayawada", address: "Govt. Polytechnic College Campus, Near Benz Circle, Vijayawada - 520008 (AP)", plugAndPlay: 234, rawSpaceSqft: 14868 },
  { city: "Warangal", address: "Kakatiya IT Park, H. No. 2-5-906/1,2, Circuit House Road, Hanamkonda, Warangal - 506001 (TS)", plugAndPlay: 64 },
];
