/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SuccessStoriesRouteImport } from './routes/success-stories'
import { Route as SubmitRouteImport } from './routes/submit'
import { Route as StartupsRouteImport } from './routes/startups'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OpportunitiesRouteImport } from './routes/opportunities'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as NewsletterRouteImport } from './routes/newsletter'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InvestorsRouteImport } from './routes/investors'
import { Route as IncubatorsRouteImport } from './routes/incubators'
import { Route as FundingRouteImport } from './routes/funding'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CalculatorRouteImport } from './routes/calculator'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AcceleratorsRouteImport } from './routes/accelerators'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StartupsIndexRouteImport } from './routes/startups.index'
import { Route as ResourcesIndexRouteImport } from './routes/resources.index'
import { Route as OpportunitiesIndexRouteImport } from './routes/opportunities.index'
import { Route as InvestorsIndexRouteImport } from './routes/investors.index'
import { Route as StartupsIdRouteImport } from './routes/startups.$id'
import { Route as ResourcesSlugRouteImport } from './routes/resources.$slug'
import { Route as OpportunitiesIdRouteImport } from './routes/opportunities.$id'
import { Route as InvestorsIdRouteImport } from './routes/investors.$id'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as ApiMcpRouteImport } from './routes/api/mcp'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SuccessStoriesRoute = SuccessStoriesRouteImport.update({
  id: '/success-stories',
  path: '/success-stories',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmitRoute = SubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const StartupsRoute = StartupsRouteImport.update({
  id: '/startups',
  path: '/startups',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesRoute = OpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsletterRoute = NewsletterRouteImport.update({
  id: '/newsletter',
  path: '/newsletter',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestorsRoute = InvestorsRouteImport.update({
  id: '/investors',
  path: '/investors',
  getParentRoute: () => rootRouteImport,
} as any)
const IncubatorsRoute = IncubatorsRouteImport.update({
  id: '/incubators',
  path: '/incubators',
  getParentRoute: () => rootRouteImport,
} as any)
const FundingRoute = FundingRouteImport.update({
  id: '/funding',
  path: '/funding',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorRoute = CalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceleratorsRoute = AcceleratorsRouteImport.update({
  id: '/accelerators',
  path: '/accelerators',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StartupsIndexRoute = StartupsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StartupsRoute,
} as any)
const ResourcesIndexRoute = ResourcesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ResourcesRoute,
} as any)
const OpportunitiesIndexRoute = OpportunitiesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OpportunitiesRoute,
} as any)
const InvestorsIndexRoute = InvestorsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InvestorsRoute,
} as any)
const StartupsIdRoute = StartupsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => StartupsRoute,
} as any)
const ResourcesSlugRoute = ResourcesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ResourcesRoute,
} as any)
const OpportunitiesIdRoute = OpportunitiesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => OpportunitiesRoute,
} as any)
const InvestorsIdRoute = InvestorsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => InvestorsRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpRoute = ApiMcpRouteImport.update({
  id: '/api/mcp',
  path: '/api/mcp',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accelerators': typeof AcceleratorsRoute
  '/admin': typeof AdminRoute
  '/calculator': typeof CalculatorRoute
  '/dashboard': typeof DashboardRoute
  '/funding': typeof FundingRoute
  '/incubators': typeof IncubatorsRoute
  '/investors': typeof InvestorsRouteWithChildren
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/newsletter': typeof NewsletterRoute
  '/onboarding': typeof OnboardingRoute
  '/opportunities': typeof OpportunitiesRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/resources': typeof ResourcesRouteWithChildren
  '/saved': typeof SavedRoute
  '/startups': typeof StartupsRouteWithChildren
  '/submit': typeof SubmitRoute
  '/success-stories': typeof SuccessStoriesRoute
  '/terms': typeof TermsRoute
  '/api/mcp': typeof ApiMcpRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/investors/$id': typeof InvestorsIdRoute
  '/opportunities/$id': typeof OpportunitiesIdRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/startups/$id': typeof StartupsIdRoute
  '/investors/': typeof InvestorsIndexRoute
  '/opportunities/': typeof OpportunitiesIndexRoute
  '/resources/': typeof ResourcesIndexRoute
  '/startups/': typeof StartupsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accelerators': typeof AcceleratorsRoute
  '/admin': typeof AdminRoute
  '/calculator': typeof CalculatorRoute
  '/dashboard': typeof DashboardRoute
  '/funding': typeof FundingRoute
  '/incubators': typeof IncubatorsRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/newsletter': typeof NewsletterRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/saved': typeof SavedRoute
  '/submit': typeof SubmitRoute
  '/success-stories': typeof SuccessStoriesRoute
  '/terms': typeof TermsRoute
  '/api/mcp': typeof ApiMcpRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/investors/$id': typeof InvestorsIdRoute
  '/opportunities/$id': typeof OpportunitiesIdRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/startups/$id': typeof StartupsIdRoute
  '/investors': typeof InvestorsIndexRoute
  '/opportunities': typeof OpportunitiesIndexRoute
  '/resources': typeof ResourcesIndexRoute
  '/startups': typeof StartupsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accelerators': typeof AcceleratorsRoute
  '/admin': typeof AdminRoute
  '/calculator': typeof CalculatorRoute
  '/dashboard': typeof DashboardRoute
  '/funding': typeof FundingRoute
  '/incubators': typeof IncubatorsRoute
  '/investors': typeof InvestorsRouteWithChildren
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/newsletter': typeof NewsletterRoute
  '/onboarding': typeof OnboardingRoute
  '/opportunities': typeof OpportunitiesRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/resources': typeof ResourcesRouteWithChildren
  '/saved': typeof SavedRoute
  '/startups': typeof StartupsRouteWithChildren
  '/submit': typeof SubmitRoute
  '/success-stories': typeof SuccessStoriesRoute
  '/terms': typeof TermsRoute
  '/api/mcp': typeof ApiMcpRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/investors/$id': typeof InvestorsIdRoute
  '/opportunities/$id': typeof OpportunitiesIdRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/startups/$id': typeof StartupsIdRoute
  '/investors/': typeof InvestorsIndexRoute
  '/opportunities/': typeof OpportunitiesIndexRoute
  '/resources/': typeof ResourcesIndexRoute
  '/startups/': typeof StartupsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accelerators'
    | '/admin'
    | '/calculator'
    | '/dashboard'
    | '/funding'
    | '/incubators'
    | '/investors'
    | '/login'
    | '/logout'
    | '/newsletter'
    | '/onboarding'
    | '/opportunities'
    | '/privacy'
    | '/profile'
    | '/resources'
    | '/saved'
    | '/startups'
    | '/submit'
    | '/success-stories'
    | '/terms'
    | '/api/mcp'
    | '/auth/callback'
    | '/investors/$id'
    | '/opportunities/$id'
    | '/resources/$slug'
    | '/startups/$id'
    | '/investors/'
    | '/opportunities/'
    | '/resources/'
    | '/startups/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accelerators'
    | '/admin'
    | '/calculator'
    | '/dashboard'
    | '/funding'
    | '/incubators'
    | '/login'
    | '/logout'
    | '/newsletter'
    | '/onboarding'
    | '/privacy'
    | '/profile'
    | '/saved'
    | '/submit'
    | '/success-stories'
    | '/terms'
    | '/api/mcp'
    | '/auth/callback'
    | '/investors/$id'
    | '/opportunities/$id'
    | '/resources/$slug'
    | '/startups/$id'
    | '/investors'
    | '/opportunities'
    | '/resources'
    | '/startups'
  id:
    | '__root__'
    | '/'
    | '/accelerators'
    | '/admin'
    | '/calculator'
    | '/dashboard'
    | '/funding'
    | '/incubators'
    | '/investors'
    | '/login'
    | '/logout'
    | '/newsletter'
    | '/onboarding'
    | '/opportunities'
    | '/privacy'
    | '/profile'
    | '/resources'
    | '/saved'
    | '/startups'
    | '/submit'
    | '/success-stories'
    | '/terms'
    | '/api/mcp'
    | '/auth/callback'
    | '/investors/$id'
    | '/opportunities/$id'
    | '/resources/$slug'
    | '/startups/$id'
    | '/investors/'
    | '/opportunities/'
    | '/resources/'
    | '/startups/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcceleratorsRoute: typeof AcceleratorsRoute
  AdminRoute: typeof AdminRoute
  CalculatorRoute: typeof CalculatorRoute
  DashboardRoute: typeof DashboardRoute
  FundingRoute: typeof FundingRoute
  IncubatorsRoute: typeof IncubatorsRoute
  InvestorsRoute: typeof InvestorsRouteWithChildren
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  NewsletterRoute: typeof NewsletterRoute
  OnboardingRoute: typeof OnboardingRoute
  OpportunitiesRoute: typeof OpportunitiesRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  ResourcesRoute: typeof ResourcesRouteWithChildren
  SavedRoute: typeof SavedRoute
  StartupsRoute: typeof StartupsRouteWithChildren
  SubmitRoute: typeof SubmitRoute
  SuccessStoriesRoute: typeof SuccessStoriesRoute
  TermsRoute: typeof TermsRoute
  ApiMcpRoute: typeof ApiMcpRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/success-stories': {
      id: '/success-stories'
      path: '/success-stories'
      fullPath: '/success-stories'
      preLoaderRoute: typeof SuccessStoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submit': {
      id: '/submit'
      path: '/submit'
      fullPath: '/submit'
      preLoaderRoute: typeof SubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/startups': {
      id: '/startups'
      path: '/startups'
      fullPath: '/startups'
      preLoaderRoute: typeof StartupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities': {
      id: '/opportunities'
      path: '/opportunities'
      fullPath: '/opportunities'
      preLoaderRoute: typeof OpportunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsletter': {
      id: '/newsletter'
      path: '/newsletter'
      fullPath: '/newsletter'
      preLoaderRoute: typeof NewsletterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investors': {
      id: '/investors'
      path: '/investors'
      fullPath: '/investors'
      preLoaderRoute: typeof InvestorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incubators': {
      id: '/incubators'
      path: '/incubators'
      fullPath: '/incubators'
      preLoaderRoute: typeof IncubatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/funding': {
      id: '/funding'
      path: '/funding'
      fullPath: '/funding'
      preLoaderRoute: typeof FundingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculator': {
      id: '/calculator'
      path: '/calculator'
      fullPath: '/calculator'
      preLoaderRoute: typeof CalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accelerators': {
      id: '/accelerators'
      path: '/accelerators'
      fullPath: '/accelerators'
      preLoaderRoute: typeof AcceleratorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/startups/': {
      id: '/startups/'
      path: '/'
      fullPath: '/startups/'
      preLoaderRoute: typeof StartupsIndexRouteImport
      parentRoute: typeof StartupsRoute
    }
    '/resources/': {
      id: '/resources/'
      path: '/'
      fullPath: '/resources/'
      preLoaderRoute: typeof ResourcesIndexRouteImport
      parentRoute: typeof ResourcesRoute
    }
    '/opportunities/': {
      id: '/opportunities/'
      path: '/'
      fullPath: '/opportunities/'
      preLoaderRoute: typeof OpportunitiesIndexRouteImport
      parentRoute: typeof OpportunitiesRoute
    }
    '/investors/': {
      id: '/investors/'
      path: '/'
      fullPath: '/investors/'
      preLoaderRoute: typeof InvestorsIndexRouteImport
      parentRoute: typeof InvestorsRoute
    }
    '/startups/$id': {
      id: '/startups/$id'
      path: '/$id'
      fullPath: '/startups/$id'
      preLoaderRoute: typeof StartupsIdRouteImport
      parentRoute: typeof StartupsRoute
    }
    '/resources/$slug': {
      id: '/resources/$slug'
      path: '/$slug'
      fullPath: '/resources/$slug'
      preLoaderRoute: typeof ResourcesSlugRouteImport
      parentRoute: typeof ResourcesRoute
    }
    '/opportunities/$id': {
      id: '/opportunities/$id'
      path: '/$id'
      fullPath: '/opportunities/$id'
      preLoaderRoute: typeof OpportunitiesIdRouteImport
      parentRoute: typeof OpportunitiesRoute
    }
    '/investors/$id': {
      id: '/investors/$id'
      path: '/$id'
      fullPath: '/investors/$id'
      preLoaderRoute: typeof InvestorsIdRouteImport
      parentRoute: typeof InvestorsRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp': {
      id: '/api/mcp'
      path: '/api/mcp'
      fullPath: '/api/mcp'
      preLoaderRoute: typeof ApiMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface InvestorsRouteChildren {
  InvestorsIdRoute: typeof InvestorsIdRoute
  InvestorsIndexRoute: typeof InvestorsIndexRoute
}

const InvestorsRouteChildren: InvestorsRouteChildren = {
  InvestorsIdRoute: InvestorsIdRoute,
  InvestorsIndexRoute: InvestorsIndexRoute,
}

const InvestorsRouteWithChildren = InvestorsRoute._addFileChildren(
  InvestorsRouteChildren,
)

interface OpportunitiesRouteChildren {
  OpportunitiesIdRoute: typeof OpportunitiesIdRoute
  OpportunitiesIndexRoute: typeof OpportunitiesIndexRoute
}

const OpportunitiesRouteChildren: OpportunitiesRouteChildren = {
  OpportunitiesIdRoute: OpportunitiesIdRoute,
  OpportunitiesIndexRoute: OpportunitiesIndexRoute,
}

const OpportunitiesRouteWithChildren = OpportunitiesRoute._addFileChildren(
  OpportunitiesRouteChildren,
)

interface ResourcesRouteChildren {
  ResourcesSlugRoute: typeof ResourcesSlugRoute
  ResourcesIndexRoute: typeof ResourcesIndexRoute
}

const ResourcesRouteChildren: ResourcesRouteChildren = {
  ResourcesSlugRoute: ResourcesSlugRoute,
  ResourcesIndexRoute: ResourcesIndexRoute,
}

const ResourcesRouteWithChildren = ResourcesRoute._addFileChildren(
  ResourcesRouteChildren,
)

interface StartupsRouteChildren {
  StartupsIdRoute: typeof StartupsIdRoute
  StartupsIndexRoute: typeof StartupsIndexRoute
}

const StartupsRouteChildren: StartupsRouteChildren = {
  StartupsIdRoute: StartupsIdRoute,
  StartupsIndexRoute: StartupsIndexRoute,
}

const StartupsRouteWithChildren = StartupsRoute._addFileChildren(
  StartupsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcceleratorsRoute: AcceleratorsRoute,
  AdminRoute: AdminRoute,
  CalculatorRoute: CalculatorRoute,
  DashboardRoute: DashboardRoute,
  FundingRoute: FundingRoute,
  IncubatorsRoute: IncubatorsRoute,
  InvestorsRoute: InvestorsRouteWithChildren,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  NewsletterRoute: NewsletterRoute,
  OnboardingRoute: OnboardingRoute,
  OpportunitiesRoute: OpportunitiesRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  ResourcesRoute: ResourcesRouteWithChildren,
  SavedRoute: SavedRoute,
  StartupsRoute: StartupsRouteWithChildren,
  SubmitRoute: SubmitRoute,
  SuccessStoriesRoute: SuccessStoriesRoute,
  TermsRoute: TermsRoute,
  ApiMcpRoute: ApiMcpRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
