/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuccessStoriesRouteImport } from './routes/success-stories'
import { Route as SubmitRouteImport } from './routes/submit'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OpportunitiesRouteImport } from './routes/opportunities'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as NewsletterRouteImport } from './routes/newsletter'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IncubatorsRouteImport } from './routes/incubators'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CalculatorRouteImport } from './routes/calculator'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AcceleratorsRouteImport } from './routes/accelerators'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResourcesIndexRouteImport } from './routes/resources.index'
import { Route as OpportunitiesIndexRouteImport } from './routes/opportunities.index'
import { Route as ResourcesSlugRouteImport } from './routes/resources.$slug'
import { Route as OpportunitiesIdRouteImport } from './routes/opportunities.$id'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'

const SuccessStoriesRoute = SuccessStoriesRouteImport.update({
  id: '/success-stories',
  path: '/success-stories',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmitRoute = SubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesRoute = OpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsletterRoute = NewsletterRouteImport.update({
  id: '/newsletter',
  path: '/newsletter',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IncubatorsRoute = IncubatorsRouteImport.update({
  id: '/incubators',
  path: '/incubators',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorRoute = CalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceleratorsRoute = AcceleratorsRouteImport.update({
  id: '/accelerators',
  path: '/accelerators',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesIndexRoute = ResourcesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ResourcesRoute,
} as any)
const OpportunitiesIndexRoute = OpportunitiesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OpportunitiesRoute,
} as any)
const ResourcesSlugRoute = ResourcesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ResourcesRoute,
} as any)
const OpportunitiesIdRoute = OpportunitiesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => OpportunitiesRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accelerators': typeof AcceleratorsRoute
  '/admin': typeof AdminRoute
  '/calculator': typeof CalculatorRoute
  '/dashboard': typeof DashboardRoute
  '/incubators': typeof IncubatorsRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/newsletter': typeof NewsletterRoute
  '/onboarding': typeof OnboardingRoute
  '/opportunities': typeof OpportunitiesRouteWithChildren
  '/profile': typeof ProfileRoute
  '/resources': typeof ResourcesRouteWithChildren
  '/saved': typeof SavedRoute
  '/submit': typeof SubmitRoute
  '/success-stories': typeof SuccessStoriesRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/opportunities/$id': typeof OpportunitiesIdRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/opportunities/': typeof OpportunitiesIndexRoute
  '/resources/': typeof ResourcesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accelerators': typeof AcceleratorsRoute
  '/admin': typeof AdminRoute
  '/calculator': typeof CalculatorRoute
  '/dashboard': typeof DashboardRoute
  '/incubators': typeof IncubatorsRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/newsletter': typeof NewsletterRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/saved': typeof SavedRoute
  '/submit': typeof SubmitRoute
  '/success-stories': typeof SuccessStoriesRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/opportunities/$id': typeof OpportunitiesIdRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/opportunities': typeof OpportunitiesIndexRoute
  '/resources': typeof ResourcesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accelerators': typeof AcceleratorsRoute
  '/admin': typeof AdminRoute
  '/calculator': typeof CalculatorRoute
  '/dashboard': typeof DashboardRoute
  '/incubators': typeof IncubatorsRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/newsletter': typeof NewsletterRoute
  '/onboarding': typeof OnboardingRoute
  '/opportunities': typeof OpportunitiesRouteWithChildren
  '/profile': typeof ProfileRoute
  '/resources': typeof ResourcesRouteWithChildren
  '/saved': typeof SavedRoute
  '/submit': typeof SubmitRoute
  '/success-stories': typeof SuccessStoriesRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/opportunities/$id': typeof OpportunitiesIdRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/opportunities/': typeof OpportunitiesIndexRoute
  '/resources/': typeof ResourcesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accelerators'
    | '/admin'
    | '/calculator'
    | '/dashboard'
    | '/incubators'
    | '/login'
    | '/logout'
    | '/newsletter'
    | '/onboarding'
    | '/opportunities'
    | '/profile'
    | '/resources'
    | '/saved'
    | '/submit'
    | '/success-stories'
    | '/auth/callback'
    | '/opportunities/$id'
    | '/resources/$slug'
    | '/opportunities/'
    | '/resources/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accelerators'
    | '/admin'
    | '/calculator'
    | '/dashboard'
    | '/incubators'
    | '/login'
    | '/logout'
    | '/newsletter'
    | '/onboarding'
    | '/profile'
    | '/saved'
    | '/submit'
    | '/success-stories'
    | '/auth/callback'
    | '/opportunities/$id'
    | '/resources/$slug'
    | '/opportunities'
    | '/resources'
  id:
    | '__root__'
    | '/'
    | '/accelerators'
    | '/admin'
    | '/calculator'
    | '/dashboard'
    | '/incubators'
    | '/login'
    | '/logout'
    | '/newsletter'
    | '/onboarding'
    | '/opportunities'
    | '/profile'
    | '/resources'
    | '/saved'
    | '/submit'
    | '/success-stories'
    | '/auth/callback'
    | '/opportunities/$id'
    | '/resources/$slug'
    | '/opportunities/'
    | '/resources/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcceleratorsRoute: typeof AcceleratorsRoute
  AdminRoute: typeof AdminRoute
  CalculatorRoute: typeof CalculatorRoute
  DashboardRoute: typeof DashboardRoute
  IncubatorsRoute: typeof IncubatorsRoute
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  NewsletterRoute: typeof NewsletterRoute
  OnboardingRoute: typeof OnboardingRoute
  OpportunitiesRoute: typeof OpportunitiesRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  ResourcesRoute: typeof ResourcesRouteWithChildren
  SavedRoute: typeof SavedRoute
  SubmitRoute: typeof SubmitRoute
  SuccessStoriesRoute: typeof SuccessStoriesRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/success-stories': {
      id: '/success-stories'
      path: '/success-stories'
      fullPath: '/success-stories'
      preLoaderRoute: typeof SuccessStoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submit': {
      id: '/submit'
      path: '/submit'
      fullPath: '/submit'
      preLoaderRoute: typeof SubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities': {
      id: '/opportunities'
      path: '/opportunities'
      fullPath: '/opportunities'
      preLoaderRoute: typeof OpportunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsletter': {
      id: '/newsletter'
      path: '/newsletter'
      fullPath: '/newsletter'
      preLoaderRoute: typeof NewsletterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incubators': {
      id: '/incubators'
      path: '/incubators'
      fullPath: '/incubators'
      preLoaderRoute: typeof IncubatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculator': {
      id: '/calculator'
      path: '/calculator'
      fullPath: '/calculator'
      preLoaderRoute: typeof CalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accelerators': {
      id: '/accelerators'
      path: '/accelerators'
      fullPath: '/accelerators'
      preLoaderRoute: typeof AcceleratorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/': {
      id: '/resources/'
      path: '/'
      fullPath: '/resources/'
      preLoaderRoute: typeof ResourcesIndexRouteImport
      parentRoute: typeof ResourcesRoute
    }
    '/opportunities/': {
      id: '/opportunities/'
      path: '/'
      fullPath: '/opportunities/'
      preLoaderRoute: typeof OpportunitiesIndexRouteImport
      parentRoute: typeof OpportunitiesRoute
    }
    '/resources/$slug': {
      id: '/resources/$slug'
      path: '/$slug'
      fullPath: '/resources/$slug'
      preLoaderRoute: typeof ResourcesSlugRouteImport
      parentRoute: typeof ResourcesRoute
    }
    '/opportunities/$id': {
      id: '/opportunities/$id'
      path: '/$id'
      fullPath: '/opportunities/$id'
      preLoaderRoute: typeof OpportunitiesIdRouteImport
      parentRoute: typeof OpportunitiesRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface OpportunitiesRouteChildren {
  OpportunitiesIdRoute: typeof OpportunitiesIdRoute
  OpportunitiesIndexRoute: typeof OpportunitiesIndexRoute
}

const OpportunitiesRouteChildren: OpportunitiesRouteChildren = {
  OpportunitiesIdRoute: OpportunitiesIdRoute,
  OpportunitiesIndexRoute: OpportunitiesIndexRoute,
}

const OpportunitiesRouteWithChildren = OpportunitiesRoute._addFileChildren(
  OpportunitiesRouteChildren,
)

interface ResourcesRouteChildren {
  ResourcesSlugRoute: typeof ResourcesSlugRoute
  ResourcesIndexRoute: typeof ResourcesIndexRoute
}

const ResourcesRouteChildren: ResourcesRouteChildren = {
  ResourcesSlugRoute: ResourcesSlugRoute,
  ResourcesIndexRoute: ResourcesIndexRoute,
}

const ResourcesRouteWithChildren = ResourcesRoute._addFileChildren(
  ResourcesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcceleratorsRoute: AcceleratorsRoute,
  AdminRoute: AdminRoute,
  CalculatorRoute: CalculatorRoute,
  DashboardRoute: DashboardRoute,
  IncubatorsRoute: IncubatorsRoute,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  NewsletterRoute: NewsletterRoute,
  OnboardingRoute: OnboardingRoute,
  OpportunitiesRoute: OpportunitiesRouteWithChildren,
  ProfileRoute: ProfileRoute,
  ResourcesRoute: ResourcesRouteWithChildren,
  SavedRoute: SavedRoute,
  SubmitRoute: SubmitRoute,
  SuccessStoriesRoute: SuccessStoriesRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
